// Code generated by troptgen. DO NOT EDIT.

package trcache_rueidis

import (
	trcache "github.com/rrgmc/trcache"
	"time"
)

func WithDefaultClientSideDuration[K comparable, V any](duration time.Duration) trcache.RootOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/options.DefaultClientSideDuration"
	const optionHash = uint64(0x489a2dc94a6654a4)
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case options[K, V]:
			opt.OptDefaultClientSideDuration(duration)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithDefaultDuration[K comparable, V any](duration time.Duration) trcache.RootOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/options.DefaultDuration"
	const optionHash = uint64(0x579e5fa1ad8c6410)
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case options[K, V]:
			opt.OptDefaultDuration(duration)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithKeyCodec[K comparable, V any](keyCodec trcache.KeyCodec[K]) trcache.RootOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/options.KeyCodec"
	const optionHash = uint64(0xc7cfddb3c3ce9420)
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case options[K, V]:
			opt.OptKeyCodec(keyCodec)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithRedisDelFunc[K comparable, V any](redisDelFunc RedisDelFunc[K, V]) trcache.RootOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/options.RedisDelFunc"
	const optionHash = uint64(0xbaf42861c1106cab)
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case options[K, V]:
			opt.OptRedisDelFunc(redisDelFunc)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithRedisGetFunc[K comparable, V any](redisGetFunc RedisGetFunc[K, V]) trcache.RootOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/options.RedisGetFunc"
	const optionHash = uint64(0xc028559f5d355778)
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case options[K, V]:
			opt.OptRedisGetFunc(redisGetFunc)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithRedisSetFunc[K comparable, V any](redisSetFunc RedisSetFunc[K, V]) trcache.RootOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/options.RedisSetFunc"
	const optionHash = uint64(0xc335e08e81dd735c)
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case options[K, V]:
			opt.OptRedisSetFunc(redisSetFunc)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithValidator[K comparable, V any](validator trcache.Validator[V]) trcache.RootOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/options.Validator"
	const optionHash = uint64(0xb87de37bdcab5a69)
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case options[K, V]:
			opt.OptValidator(validator)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithValueCodec[K comparable, V any](valueCodec trcache.Codec[V]) trcache.RootOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/options.ValueCodec"
	const optionHash = uint64(0x60e10572ffe632fa)
	return trcache.RootOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case options[K, V]:
			opt.OptValueCodec(valueCodec)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithGetClientSideDuration[K comparable, V any](duration time.Duration) trcache.GetOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/getOptions.ClientSideDuration"
	const optionHash = uint64(0xe1d62744f74f7407)
	return trcache.GetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case getOptions[K, V]:
			opt.OptClientSideDuration(duration)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithGetCustomParams[K comparable, V any](customParams interface{}) trcache.GetOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/getOptions.CustomParams"
	const optionHash = uint64(0xd4c41ff523a8fc)
	return trcache.GetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case getOptions[K, V]:
			opt.OptCustomParams(customParams)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithGetRedisGetFunc[K comparable, V any](redisGetFunc RedisGetFunc[K, V]) trcache.GetOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/getOptions.RedisGetFunc"
	const optionHash = uint64(0x4f44238560ff82e2)
	return trcache.GetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case getOptions[K, V]:
			opt.OptRedisGetFunc(redisGetFunc)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithSetCustomParams[K comparable, V any](customParams interface{}) trcache.SetOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/setOptions.CustomParams"
	const optionHash = uint64(0x1cba6480dc9e4630)
	return trcache.SetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case setOptions[K, V]:
			opt.OptCustomParams(customParams)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithSetRedisSetFunc[K comparable, V any](redisSetFunc RedisSetFunc[K, V]) trcache.SetOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/setOptions.RedisSetFunc"
	const optionHash = uint64(0x7272ef0446723362)
	return trcache.SetOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case setOptions[K, V]:
			opt.OptRedisSetFunc(redisSetFunc)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithDeleteCustomParams[K comparable, V any](customParams interface{}) trcache.DeleteOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/deleteOptions.CustomParams"
	const optionHash = uint64(0xea2924df77c19627)
	return trcache.DeleteOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case deleteOptions[K, V]:
			opt.OptCustomParams(customParams)
			return true
		}
		return false
	}, optionName, optionHash)
}
func WithDeleteRedisDelFunc[K comparable, V any](redisDelFunc RedisDelFunc[K, V]) trcache.DeleteOption {
	const optionName = "github.com/rrgmc/trcache-rueidis/deleteOptions.RedisDelFunc"
	const optionHash = uint64(0x402823f3f1ac6622)
	return trcache.DeleteOptionFunc(func(o any) bool {
		switch opt := o.(type) {
		case deleteOptions[K, V]:
			opt.OptRedisDelFunc(redisDelFunc)
			return true
		}
		return false
	}, optionName, optionHash)
}

type rootOptionsImpl[K comparable, V any] struct {
	callDefaultDeleteOptions  []trcache.DeleteOption
	callDefaultGetOptions     []trcache.GetOption
	callDefaultSetOptions     []trcache.SetOption
	defaultClientSideDuration time.Duration
	defaultDuration           time.Duration
	keyCodec                  trcache.KeyCodec[K]
	name                      string
	redisDelFunc              RedisDelFunc[K, V]
	redisGetFunc              RedisGetFunc[K, V]
	redisSetFunc              RedisSetFunc[K, V]
	validator                 trcache.Validator[V]
	valueCodec                trcache.Codec[V]
}

var _ options[string, string] = &rootOptionsImpl[string, string]{}

func (o *rootOptionsImpl[K, V]) OptCallDefaultDeleteOptions(options ...trcache.DeleteOption) {
	o.callDefaultDeleteOptions = options
}
func (o *rootOptionsImpl[K, V]) OptCallDefaultGetOptions(options ...trcache.GetOption) {
	o.callDefaultGetOptions = options
}
func (o *rootOptionsImpl[K, V]) OptCallDefaultSetOptions(options ...trcache.SetOption) {
	o.callDefaultSetOptions = options
}
func (o *rootOptionsImpl[K, V]) OptDefaultClientSideDuration(duration time.Duration) {
	o.defaultClientSideDuration = duration
}
func (o *rootOptionsImpl[K, V]) OptDefaultDuration(duration time.Duration) {
	o.defaultDuration = duration
}
func (o *rootOptionsImpl[K, V]) OptKeyCodec(keyCodec trcache.KeyCodec[K]) {
	o.keyCodec = keyCodec
}
func (o *rootOptionsImpl[K, V]) OptName(name string) {
	o.name = name
}
func (o *rootOptionsImpl[K, V]) OptRedisDelFunc(redisDelFunc RedisDelFunc[K, V]) {
	o.redisDelFunc = redisDelFunc
}
func (o *rootOptionsImpl[K, V]) OptRedisGetFunc(redisGetFunc RedisGetFunc[K, V]) {
	o.redisGetFunc = redisGetFunc
}
func (o *rootOptionsImpl[K, V]) OptRedisSetFunc(redisSetFunc RedisSetFunc[K, V]) {
	o.redisSetFunc = redisSetFunc
}
func (o *rootOptionsImpl[K, V]) OptValidator(validator trcache.Validator[V]) {
	o.validator = validator
}
func (o *rootOptionsImpl[K, V]) OptValueCodec(valueCodec trcache.Codec[V]) {
	o.valueCodec = valueCodec
}

type getOptionsImpl[K comparable, V any] struct {
	clientSideDuration time.Duration
	customParams       interface{}
	redisGetFunc       RedisGetFunc[K, V]
}

var _ getOptions[string, string] = &getOptionsImpl[string, string]{}

func (o *getOptionsImpl[K, V]) OptClientSideDuration(duration time.Duration) {
	o.clientSideDuration = duration
}
func (o *getOptionsImpl[K, V]) OptCustomParams(customParams interface{}) {
	o.customParams = customParams
}
func (o *getOptionsImpl[K, V]) OptRedisGetFunc(redisGetFunc RedisGetFunc[K, V]) {
	o.redisGetFunc = redisGetFunc
}

type setOptionsImpl[K comparable, V any] struct {
	customParams interface{}
	duration     time.Duration
	redisSetFunc RedisSetFunc[K, V]
}

var _ setOptions[string, string] = &setOptionsImpl[string, string]{}

func (o *setOptionsImpl[K, V]) OptCustomParams(customParams interface{}) {
	o.customParams = customParams
}
func (o *setOptionsImpl[K, V]) OptDuration(duration time.Duration) {
	o.duration = duration
}
func (o *setOptionsImpl[K, V]) OptRedisSetFunc(redisSetFunc RedisSetFunc[K, V]) {
	o.redisSetFunc = redisSetFunc
}

type deleteOptionsImpl[K comparable, V any] struct {
	customParams interface{}
	redisDelFunc RedisDelFunc[K, V]
}

var _ deleteOptions[string, string] = &deleteOptionsImpl[string, string]{}

func (o *deleteOptionsImpl[K, V]) OptCustomParams(customParams interface{}) {
	o.customParams = customParams
}
func (o *deleteOptionsImpl[K, V]) OptRedisDelFunc(redisDelFunc RedisDelFunc[K, V]) {
	o.redisDelFunc = redisDelFunc
}
